version: '3'

services:
  vue:
    build: ./app
    container_name: vue-container
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    volumes: 
      - type: bind
        source: ./app
        target: /app

